const RolesConfig = {
  'Art Director': 'D1',
  'Caricaturist': 'D2',
  'Costume Designer': 'D3',
  'Fashion Designer': 'D4',
  'Floral Crew': 'D5',
  'Floral Designer': 'D6',
  'Graphic Designer': 'D7',
  'Lighting Designer': 'D8',
  'Muralist': 'D9',
  'Set Designer': 'D10',
  'Stage Designer': 'D11',
  'Visual Designer': 'D12',
  'Aerial Performer': 'E1',
  'Casino Dealer': 'E2',
  'Dancer': 'E3',
  'DJ': 'E4',
  'Emcee': 'E5',
  'Entertainer': 'E6',
  'Juggler': 'E7',
  'Master of Ceremonies': 'E8',
  'Musician': 'E9',
  'Assistant Banquet Manager': 'F1',
  'Banquet Manager': 'F2',
  'Barback': 'F3',
  'Barista': 'F4',
  'Bartender': 'F5',
  'Busser': 'F6',
  'Cake Artist': 'F7',
  'Caterer': 'F8',
  'Catering Crew': 'F9',
  'Chef': 'F10',
  'Concessions Vendor': 'F11',
  'Cook': 'F12',
  'Dishwasher': 'F13',
  'General Kitchen Staff': 'F14',
  'Line Cook': 'F15',
  'Mixologist': 'F16',
  'Prep Cook': 'F17',
  'Server': 'F18',
  'Sous Chef': 'F19',
  'Concierge': 'G1',
  'Customer Service': 'G2',
  'Exhibition Attendant': 'G3',
  'Front of House': 'G4',
  'Greeter': 'G5',
  'Host / Hostess': 'G6',
  'Registration Desk Attendant': 'G7',
  'Ticketing Attendant': 'G8',
  'Usher': 'G9',
  'Accountant': 'O1',
  'Art Installer': 'O2',
  'Babysitter': 'O3',
  'Child Care Professional': 'O4',
  'Officiant': 'O5',
  'Pet Sitter': 'O6',
  'Room Monitor': 'O7',
  'Silent Auction Staff': 'O8',
  'Sports Official': 'O9',
  'Volunteer': 'O10',
  'Volunteer Coordinator': 'O11',
  'Boat Captain': 'PRA1',
  'Boat Crew': 'PRA2',
  'Cleaning Crew': 'PRA3',
  'Construction Crew': 'PRA4',
  'Crew Chief': 'PRA5',
  'Delivery Driver': 'PRA6',
  'Directional Staff': 'PRA7',
  'Driver': 'PRA8',
  'Event Setup Crew': 'PRA9',
  'General Crew': 'PRA10',
  'Landscaping Crew': 'PRA11',
  'Painter': 'PRA12',
  'Parking Attendant': 'PRA13',
  'Security Guard': 'PRA14',
  'Stocker': 'PRA15',
  'Transportation Planner': 'PRA16',
  'Waste Management Crew': 'PRA17',
  'Event Coordinator': 'PRO18',
  'Event Marketing Manager': 'PRO19',
  'Event Planner': 'PRO20',
  'Event Producer': 'PRO21',
  'Event Promoter': 'PRO22',
  'Media Relations Manager': 'PRO23',
  'Public Relations Manager': 'PRO24',
  'Publicist': 'PRO25',
  'Social Media Manager': 'PRO26',
  'Staff Director': 'PRO27',
  'Brand Ambassador': 'PRM28',
  'Event Marketer': 'PRM29',
  'Merchandise Vendor': 'PRM30',
  'Model': 'PRM31',
  'Product Promoter': 'PRM32',
  'Sales': 'PRM33',
  'Visual Merchandiser': 'PRM34',
  'Artist Hospitality Manager': 'TL1',
  'Artist Relations': 'TL2',
  'A/V Technician': 'TAV3',
  'Assistant Camera Operator': 'TAV4',
  'Audio Crew': 'TAV5',
  'Audio Post-production': 'TAV6',
  'Camera Operator': 'TAV7',
  'Director of Photography': 'TAV8',
  'Drone Operator': 'TAV9',
  'Photo Retoucher': 'TAV10',
  'Photographer': 'TAV11',
  'Photography Assistant': 'TAV12',
  'Photography Crew': 'TAV13',
  'Photography Post-production': 'TAV14',
  'Production Assistant': 'TAV15',
  'Production Crew': 'TAV17',
  'Production Director': 'TAV18',
  'Production Manager': 'TAV19',
  'Sound Engineer': 'TAV20',
  'Sound Mixer': 'TAV21',
  'Touring Engineer': 'TAV22',
  'Video/Film Crew': 'TAV23',
  'Video/Film Post-production': 'TAV24',
  'Videographer': 'TAV25',
  'Videography Assistant': 'TAV26',
  'Communications Technician': 'TS27',
  'Electrician': 'TS28',
  'Equipment Repair Technician': 'TS29',
  'IT & Network Technician': 'TS30',
  'Lighting Operator': 'TS31',
  'Lighting Technician': 'TS32',
  'Stage Manager': 'TS33',
  'Stage Rigger': 'TS34',
  'Tech Support': 'TS35',
  'Zone Manager': 'TS36',
  'Aesthetician': 'W1',
  'Assistant Stylist': 'W2',
  'Chiropractor': 'W3',
  'Hair Stylist': 'W4',
  'Make-up Artist': 'W5',
  'Masseuse': 'W6',
  'Model Prep Crew': 'W7'
};

const intercomRole = (rolesArray) => {
  if(Array.isArray(rolesArray)) {
    rolesArray = rolesArray.map(role => {
      return RolesConfig[role];
    });
    let intercomRolesString = rolesArray.join(',');
    return intercomRolesString.substring(0, 255);
  }
  return '';
};

module.exports = intercomRole;
